name: Update Last Updated Date on Push

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger this on

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get the current date and update the last_updated.json file
      - name: Update last_updated.json
        run: |
          # Get the current date
          current_date=$(date +"%B %d, %Y")

          # Update last_updated.json file with the current date
          echo '{
            "last_updated": "'$current_date'"
          }' > assets/data/last_updated.json

      # Commit and push the updated last_updated.json file back to the repository
      - name: Commit updated last_updated.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/data/last_updated.json
          git commit -m "Update last_updated.json with current date"
          git push
